// Protocol buffer schema for rinnsal event logging.
//
// To regenerate events_pb2.py:
//   python -m grpc_tools.protoc --python_out=. -I. events.proto

// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file events.proto (package rinnsal, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file events.proto.
 */
export const file_events: GenFile = /*@__PURE__*/
  fileDesc("CgxldmVudHMucHJvdG8SB3Jpbm5zYWwixQEKBUV2ZW50EhEKCXRpbWVzdGFtcBgBIAEoARIRCglpdGVyYXRpb24YAiABKAMSIQoGc2NhbGFyGAMgASgLMg8ucmlubnNhbC5TY2FsYXJIABIdCgR0ZXh0GAQgASgLMg0ucmlubnNhbC5UZXh0SAASIQoGZmlndXJlGAUgASgLMg8ucmlubnNhbC5GaWd1cmVIABIpCgpjaGVja3BvaW50GAYgASgLMhMucmlubnNhbC5DaGVja3BvaW50SABCBgoEZGF0YSIkCgZTY2FsYXISCwoDdGFnGAEgASgJEg0KBXZhbHVlGAIgASgBIiIKBFRleHQSCwoDdGFnGAEgASgJEg0KBXZhbHVlGAIgASgJIkcKBkZpZ3VyZRILCgN0YWcYASABKAkSEwoLaW50ZXJhY3RpdmUYAiABKAgSDQoFaW1hZ2UYAyABKAwSDAoEZGF0YRgEIAEoDCInCgpDaGVja3BvaW50EgsKA3RhZxgBIAEoCRIMCgRkYXRhGAIgASgMYgZwcm90bzM");

/**
 * @generated from message rinnsal.Event
 */
export type Event = Message<"rinnsal.Event"> & {
  /**
   * @generated from field: double timestamp = 1;
   */
  timestamp: number;

  /**
   * @generated from field: int64 iteration = 2;
   */
  iteration: bigint;

  /**
   * @generated from oneof rinnsal.Event.data
   */
  data: {
    /**
     * @generated from field: rinnsal.Scalar scalar = 3;
     */
    value: Scalar;
    case: "scalar";
  } | {
    /**
     * @generated from field: rinnsal.Text text = 4;
     */
    value: Text;
    case: "text";
  } | {
    /**
     * @generated from field: rinnsal.Figure figure = 5;
     */
    value: Figure;
    case: "figure";
  } | {
    /**
     * @generated from field: rinnsal.Checkpoint checkpoint = 6;
     */
    value: Checkpoint;
    case: "checkpoint";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message rinnsal.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_events, 0);

/**
 * @generated from message rinnsal.Scalar
 */
export type Scalar = Message<"rinnsal.Scalar"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: double value = 2;
   */
  value: number;
};

/**
 * Describes the message rinnsal.Scalar.
 * Use `create(ScalarSchema)` to create a new message.
 */
export const ScalarSchema: GenMessage<Scalar> = /*@__PURE__*/
  messageDesc(file_events, 1);

/**
 * @generated from message rinnsal.Text
 */
export type Text = Message<"rinnsal.Text"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message rinnsal.Text.
 * Use `create(TextSchema)` to create a new message.
 */
export const TextSchema: GenMessage<Text> = /*@__PURE__*/
  messageDesc(file_events, 2);

/**
 * @generated from message rinnsal.Figure
 */
export type Figure = Message<"rinnsal.Figure"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: bool interactive = 2;
   */
  interactive: boolean;

  /**
   * PNG bytes (non-interactive)
   *
   * @generated from field: bytes image = 3;
   */
  image: Uint8Array;

  /**
   * cloudpickle bytes (interactive)
   *
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;
};

/**
 * Describes the message rinnsal.Figure.
 * Use `create(FigureSchema)` to create a new message.
 */
export const FigureSchema: GenMessage<Figure> = /*@__PURE__*/
  messageDesc(file_events, 3);

/**
 * @generated from message rinnsal.Checkpoint
 */
export type Checkpoint = Message<"rinnsal.Checkpoint"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message rinnsal.Checkpoint.
 * Use `create(CheckpointSchema)` to create a new message.
 */
export const CheckpointSchema: GenMessage<Checkpoint> = /*@__PURE__*/
  messageDesc(file_events, 4);

