# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x07rinnsal\"\xa2\x02\n\x05\x45vent\x12\x1c\n\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x12\x1c\n\titeration\x18\x02 \x01(\x03R\titeration\x12)\n\x06scalar\x18\x03 \x01(\x0b\x32\x0f.rinnsal.ScalarH\x00R\x06scalar\x12#\n\x04text\x18\x04 \x01(\x0b\x32\r.rinnsal.TextH\x00R\x04text\x12)\n\x06\x66igure\x18\x05 \x01(\x0b\x32\x0f.rinnsal.FigureH\x00R\x06\x66igure\x12\x35\n\ncheckpoint\x18\x06 \x01(\x0b\x32\x13.rinnsal.CheckpointH\x00R\ncheckpoint\x12#\n\x04\x63\x61rd\x18\x07 \x01(\x0b\x32\r.rinnsal.CardH\x00R\x04\x63\x61rdB\x06\n\x04\x64\x61ta\"0\n\x06Scalar\x12\x10\n\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n\x05value\x18\x02 \x01(\x01R\x05value\".\n\x04Text\x12\x10\n\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\"f\n\x06\x46igure\x12\x10\n\x03tag\x18\x01 \x01(\tR\x03tag\x12 \n\x0binteractive\x18\x02 \x01(\x08R\x0binteractive\x12\x14\n\x05image\x18\x03 \x01(\x0cR\x05image\x12\x12\n\x04\x64\x61ta\x18\x04 \x01(\x0cR\x04\x64\x61ta\"2\n\nCheckpoint\x12\x10\n\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n\x04\x64\x61ta\x18\x02 \x01(\x0cR\x04\x64\x61ta\"t\n\x04\x43\x61rd\x12\x12\n\x04task\x18\x01 \x01(\tR\x04task\x12\x12\n\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n\x07\x63ontent\x18\x04 \x01(\tR\x07\x63ontent\x12\x14\n\x05image\x18\x05 \x01(\x0cR\x05imageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=26
  _globals['_EVENT']._serialized_end=316
  _globals['_SCALAR']._serialized_start=318
  _globals['_SCALAR']._serialized_end=366
  _globals['_TEXT']._serialized_start=368
  _globals['_TEXT']._serialized_end=414
  _globals['_FIGURE']._serialized_start=416
  _globals['_FIGURE']._serialized_end=518
  _globals['_CHECKPOINT']._serialized_start=520
  _globals['_CHECKPOINT']._serialized_end=570
  _globals['_CARD']._serialized_start=572
  _globals['_CARD']._serialized_end=688
# @@protoc_insertion_point(module_scope)
