# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x07rinnsal\"\xc5\x01\n\x05\x45vent\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x11\n\titeration\x18\x02 \x01(\x03\x12!\n\x06scalar\x18\x03 \x01(\x0b\x32\x0f.rinnsal.ScalarH\x00\x12\x1d\n\x04text\x18\x04 \x01(\x0b\x32\r.rinnsal.TextH\x00\x12!\n\x06\x66igure\x18\x05 \x01(\x0b\x32\x0f.rinnsal.FigureH\x00\x12)\n\ncheckpoint\x18\x06 \x01(\x0b\x32\x13.rinnsal.CheckpointH\x00\x42\x06\n\x04\x64\x61ta\"$\n\x06Scalar\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"\"\n\x04Text\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"8\n\x06\x46igure\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x13\n\x0binteractive\x18\x03 \x01(\x08\"\'\n\nCheckpoint\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=26
  _globals['_EVENT']._serialized_end=223
  _globals['_SCALAR']._serialized_start=225
  _globals['_SCALAR']._serialized_end=261
  _globals['_TEXT']._serialized_start=263
  _globals['_TEXT']._serialized_end=297
  _globals['_FIGURE']._serialized_start=299
  _globals['_FIGURE']._serialized_end=355
  _globals['_CHECKPOINT']._serialized_start=357
  _globals['_CHECKPOINT']._serialized_end=396
# @@protoc_insertion_point(module_scope)
