# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cevents.proto\x12\x07rinnsal"\x85\x02\n\x05\x45vent\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x11\n\titeration\x18\x02 \x01(\x03\x12!\n\x06scalar\x18\x03 \x01(\x0b\x32\x0f.rinnsal.ScalarH\x00\x12\x1d\n\x04text\x18\x04 \x01(\x0b\x32\r.rinnsal.TextH\x00\x12!\n\x06\x66igure\x18\x05 \x01(\x0b\x32\x0f.rinnsal.FigureH\x00\x12)\n\ncheckpoint\x18\x06 \x01(\x0b\x32\x13.rinnsal.CheckpointH\x00\x12\x1d\n\x04\x63\x61rd\x18\x07 \x01(\x0b\x32\r.rinnsal.CardH\x00\x12\x1f\n\x05image\x18\x08 \x01(\x0b\x32\x0e.rinnsal.ImageH\x00\x42\x06\n\x04\x64\x61ta"Q\n\x05Image\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\t"$\n\x06Scalar\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01""\n\x04Text\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t"G\n\x06\x46igure\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x13\n\x0binteractive\x18\x02 \x01(\x08\x12\r\n\x05image\x18\x03 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c"\'\n\nCheckpoint\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c"Q\n\x04\x43\x61rd\x12\x0c\n\x04task\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
