import { useEffect, useRef, useState } from "react";
import { CardComponentPayload, blobUrl } from "../../lib/api";

/* eslint-disable @typescript-eslint/no-explicit-any */
declare global {
  interface Window {
    Plotly?: { newPlot: (...args: any[]) => any };
  }
}

const PLOTLY_CDN = "https://cdn.plot.ly/plotly-2.35.2.min.js";

let _plotlyPromise: Promise<{ newPlot: (...args: any[]) => any }> | null = null;

function loadPlotlyFromCDN(): Promise<{ newPlot: (...args: any[]) => any }> {
  if (window.Plotly) return Promise.resolve(window.Plotly);
  if (_plotlyPromise) return _plotlyPromise;
  _plotlyPromise = new Promise((resolve, reject) => {
    const script = document.createElement("script");
    script.src = PLOTLY_CDN;
    script.async = true;
    script.onload = () => {
      if (window.Plotly) resolve(window.Plotly);
      else reject(new Error("plotly loaded but window.Plotly missing"));
    };
    script.onerror = () => reject(new Error(`failed to load ${PLOTLY_CDN}`));
    document.head.appendChild(script);
  });
  return _plotlyPromise;
}
/* eslint-enable @typescript-eslint/no-explicit-any */

interface Props {
  run: string;
  component: CardComponentPayload;
}

/**
 * Interactive Plotly renderer. Plotly.js is loaded dynamically the first
 * time this component mounts; the bundle is kept out of the main chunk
 * so users without plotly cards never download it.
 *
 * If the dynamic import fails (Plotly.js not bundled) we fall back to
 * the static PNG generated by kaleido on the orchestrator side.
 */
export default function PlotlyRenderer({ run, component }: Props) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [figure, setFigure] = useState<unknown | null>(null);

  // Resolve the figure JSON: inline, or via blob fetch.
  useEffect(() => {
    let cancelled = false;

    const load = async () => {
      try {
        let json: string | null = null;
        if (component.inline_json) {
          json = component.inline_json;
        } else if (component.blob_hash) {
          const r = await fetch(blobUrl(run, component.blob_hash));
          if (!r.ok) throw new Error(`blob fetch ${r.status}`);
          json = await r.text();
        }
        if (json === null) throw new Error("no plotly payload");
        if (!cancelled) setFigure(JSON.parse(json));
      } catch (e) {
        if (!cancelled) setError(String(e));
      }
    };

    void load();
    return () => { cancelled = true; };
  }, [run, component.inline_json, component.blob_hash]);

  // Render the figure once we have it AND Plotly.js is available.
  useEffect(() => {
    if (!figure || !containerRef.current) return;
    let cancelled = false;

    const render = async () => {
      try {
        // Plotly.js is loaded from CDN at runtime — keeps the rinnsal
        // viewer bundle small. If the CDN fails (offline), we fall
        // back to the static PNG generated by kaleido.
        const Plotly = await loadPlotlyFromCDN().catch(() => null);
        if (cancelled || !containerRef.current) return;
        if (!Plotly) {
          setError("plotly.js unavailable");
          return;
        }
        const fig = figure as { data?: unknown; layout?: unknown };
        Plotly.newPlot(
          containerRef.current,
          fig.data ?? [],
          fig.layout ?? {},
          { displaylogo: false, responsive: true },
        );
      } catch (e) {
        if (!cancelled) setError(String(e));
      }
    };

    void render();
    return () => { cancelled = true; };
  }, [figure]);

  if (error && component.png_blob_hash) {
    return (
      <img
        src={blobUrl(run, component.png_blob_hash)}
        alt={component.title || "plotly figure"}
        className="max-w-full rounded"
      />
    );
  }
  if (error) {
    return <div className="text-xs text-gray-400">[plotly: {error}]</div>;
  }
  return (
    <div>
      {component.title && <div className="text-sm text-gray-700 mb-1">{component.title}</div>}
      <div ref={containerRef} className="w-full h-80" />
    </div>
  );
}
